### ISSUE TITLE
Annotation Format

### ISSUE THREAD

**Issue by BITwtz** [tianqi-wang1996/DeepAccident#14]
Can you explain the format of the annotation file？ Thanks a lot.

**Comment by tianqi-wang1996** [comment]
To clarify the annotation format, I will give two examples below:
line 1
car 78.72284516674358 30.2601938920738 -2.4741850862891717 3.987684965133667 1.8508483171463013 1.6171096563339233 3.083730477344937 0.0 0.0 20017 0 False
line 2
car -11.322061738492891 -1.1220229654831542 -1.3597587620497014 6.273553371429443 2.3895740509033203 2.098191261291504 0.26862670698632135 -1.9075593327095062 3.166942064036916 1339 547 True

All the numbers are in lidar coordinate (postive x: front, positive y: right, positive z: up). The lidar is installed on the center of ego vehicle with some height.
The annotation format is:
cls_label x y z bbox_x bbox_y bbox_z  yaw_angle (in radians, range -pi ~ pi) vel_x (unit m/s)  vel_y (unit m/s) obj_id number_lidar_pts_of_this_obj flag_visible_in_cameras
for obj with obj_id bigger than 20000, it is because they are static objects provided by CARLA to decorate the scene, not the ones we spawned, thus have 0 velocity.

**Comment by muety** [comment]
So both position and velocity of detected obstacles is relative to the ego vehicle, correct? Is information about the ego vehicle's own velocity (as well as its dimensions, see #19) included somewhere as well? 

EDIT: Okay, looks like the ego vehicle is included as the actor with `obj_id = -100`  with given position, bbox and velocity. Also, velocities seems to be absolute, otherwise the ego would always have to have `(0, 0)`. But then I'm wondering why the ego's velocity differs between the object list of the follower vehicle and its own. Didn't you use ground truth information there?

**Comment by mashihan123** [comment]
> So both position and velocity of detected obstacles is relative to the ego vehicle, correct? Is information about the ego vehicle's own velocity (as well as its dimensions, see #19) included somewhere as well?
> 
> EDIT: Okay, looks like the ego vehicle is included as the actor with `obj_id = -100` with given position, bbox and velocity. Also, velocities seems to be absolute, otherwise the ego would always have to have `(0, 0)`. But then I'm wondering why the ego's velocity differs between the object list of the follower vehicle and its own. Didn't you use ground truth information there?

Hello! I'm still trying to figure out: in the infrastructure data folder, are the objects relative to the infrastructure itself (still reference point)?
And yes, I also agree that the velocities are absolute.

**Comment by JsSparkyyx** [comment]
For anyone who doesn't know where is the information about the ego vehicle's velocity. I have checked their code. It seems like the first line of the label file represents the vehicle_speed_x and vehicle_speed_y. See lines 230-231 in ./tool/data_converter/carla_converter.py
